apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus
  namespace: gatus-system
data:
  config.yaml: |
    security:
      oidc:
        issuer-url: "https://accounts.google.com"
        client-id: "${OIDC_CLIENT_ID}"
        client-secret: "${OIDC_CLIENT_SECRET}"
        redirect-url: "https://gatus.79.120.12.118.nip.io/authorization-code/callback"
        scopes: ["openid", "email", "profile"]

    metrics: true
    endpoints:
      - name: none town
        url: https://n0ne.sytes.net
        interval: 20s
        conditions:
          - "[STATUS] == 200"
      - name: internet access
        url: http://connectivitycheck.gstatic.com/generate_204
        interval: 5m
        conditions:
          - "[STATUS] == 204"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gatus
  namespace: gatus-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatus
  namespace: gatus-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatus
  template:
    metadata:
      name: gatus
      namespace: gatus-system
      labels:
        app: gatus
    spec:
      serviceAccountName: gatus
      terminationGracePeriodSeconds: 5
      containers:
        - image: ghcr.io/twin/gatus:stable
          imagePullPolicy: IfNotPresent
          name: gatus
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: gatus-oidc
                  key: OIDC_CLIENT_ID
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gatus-oidc
                  key: OIDC_CLIENT_SECRET
          resources:
            limits:
              cpu: 250m
              memory: 100M
            requests:
              cpu: 50m
              memory: 30M
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          volumeMounts:
            - mountPath: /config
              name: gatus-config
      volumes:
        - configMap:
            name: gatus
          name: gatus-config
---
apiVersion: v1
kind: Service
metadata:
  name: gatus
  namespace: gatus-system
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: gatus
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gatus-ingress
  namespace: gatus-system
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
    - host: gatus.79.120.12.118.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gatus
                port:
                  number: 8080
  tls:
    - hosts:
        - gatus.79.120.12.118.nip.io
      secretName: gatus-tls-secret
---
apiVersion: v1
kind: Namespace
metadata:
  name: gatus-system