apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./infrastructure/cert-manager
- ./infrastructure/metallb-system
- ./infrastructure/ingress-nginx
- ./infrastructure/sealed-secrets
- ./infrastructure/gatus-system
- ./production
