apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce  # Том можно монтировать на чтение и запись только одной ноде за раз
  storageClassName: local-path  # Или другой класс, поддерживаемый Talos
  resources:
    requests:
      storage: 10Gi