---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-init-script
  namespace: default
spec:
  encryptedData:
    init-db.js: AgA0YZVDqogfp90QaoAXCGK+s8oURh3ltBEQVWlSfXZztbOeVRG3oAfnZ1yMciFnnkggEsAIIwB5Mm6XH8o2rhWTQJ7jeK1Mdh7KgRCPA3ZXe7eswHWkLsCPv8lLMFi8320uhLa7DgfxRk9zwUwpM8luhpOa7qp5eS3IdaTwhiApqGeC3kxsYgEVu1sB9M7HxhlNyYXRw/h9SwcOldU5sA2r7oiFhyqSDaN8ATJJJqNg8v5JuVo0GM7bmt7INuwd5NJgoSjqcUPQ/gw4fP9Js0TzvxmROKyoesDQFhk7XRMOJ/yEx6TSDNgI3vNsogZvod4MTH4PsxHYsrkB8ef5djsBNK2tYnlFZbM8fCpYdzUW+aozepu4D/cg8cmM/DazZUokHolOasS4ttA/zrw1I/QdHKoyFwKD0DVlGeofHC6t0zYRJLQEcKPCUdit7ICPlECwyI+uv+3tRSK6M7R5HjCR9/KtBehfhPbUxzOS/+CrbQeJWBqiWnUYzLe6cIQ7B7u3RgWWGI0kK2SFUccgaOE8gb8I+yRsrZ0DPwQcGJAuInZ94L9HmgZ+67+x7Vsn+l/0K1+kvYzjrU56NtSzNuOOQVmn+5Y5yNq8VQNH6IOp/iYEAyLFxdNbaTGaInh+3Xb7w7TR9O6VOuhMUCzSSu+z3u4ldF70zwVosWdP6cjGkX9VrnG485zJAPdy3kTsTO4AVSeuf1EEFtRg2RKC2xNxCVWRcV/aNzukyD3KQCZIgli+UcWp5GUny8Z/F0PNBAt0n8niyI8Fl1jXJDKqQK9d3zHzBoixqLJz16LWg24ok1F0lhxL+uFw/A80rPOizr8rLqlvNBHEPztUo6FdhM1tpSOX5TAUnPmW4Ew6E1WYA3gPcLPew6BVWD1At3mXuNjxW7FsAudKsU3XlDzd2FkCsrNKkxBTTfUXLrHmqRcP08Gb/JAsEFK8lq8h7QoNop0e4h65Mp9xsDBlIbh+fIhIq2PP8fmX
  template:
    metadata:
      name: mongo-init-script
      namespace: default
