---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-init-script
  namespace: production
spec:
  encryptedData:
    init-db.js: AgAnp5LJ8o5OJ/Ak2tH+CxaoPQ6Z+EShC+4MsS0fZd9LQR9CaOy59dUYMeIWOi5pA1GSOEcn9GCz8p8jSHJY1SADgoA66OKIv3VjUIusPUEeuSHqbDyHjScvube4wrwJbvWp1DVRFZDXpWTAp+e76DmM/FiP9ShSApXYMHCqjl12K1j/GN6+xNHYRbgE1gzyk4tW3LyWgCsQjvbRjvNIvHADkFbvF5tTb0g+CxpXM2fMcScHIjPHhc+SygwrAkBlHW2NRC2baV0AQrX4Tmmri7U67WIJyni9uZ2cZuWPlYrLGxIccYpXzco7WoH4n5yrAePyOehirl8TNC9C8beSRoF7cXgdm0/MPFjBv4nJiK3Ey6FLKAuhO9NmEdPXj2pbriG/FXumf/6nr0mcEjw4RWMNyU9QmtmjOtJjwt/DMTDfu48HvOsIjscBk3tnN8M7utcvtKaw8AI2o9dQRQjj0phcE4MYr/DrGqWyfyNZU7MU8NJnWFx94tYBUFZXWOs3+slWkhudJ/jaRNAWbd8bAxkpNQR/OLIVZN6OOjlFCzl5Eld+DRyOsJtCpOGHMu/7AZjFSpQZxhgpEyrPAYR9mRPvkCitP1Zi4jM2ZsCMKlVBAjY8dy5BJ/wQ/ie5sDKegBJMd2AMknlYP+4NK9De+637JLeZtpNZRchpGS2JUuoNs4+4oYZgYssllNtaOgfJ9cXFGW6jveb2fqYbFsBBaFs0tYwgPz35btPALXmYLzc76dV7jzc32150eZhhq6tJsg21ldyWA4rMFIayxTN60Rb66gqo75QmVqST2OiF7piuNdt6jWmkr+uDqpupEDWLNgBfbfxm9/jecUV500oI00itmP06BSPGW7Wozw7ViYRL6dzwFB9B4TWV759Oi7dFtjcV6ZrSG6ZN54stNUCMHAJk2MoubHi8MsM25lW8aJwfhyHorQcJhI599OhLEAXYN+NwELB3weNBWNzEaKW45tsUkgOO6wpB
  template:
    metadata:
      name: mongo-init-script
      namespace: production
