---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-init-script
  namespace: production
spec:
  encryptedData:
    init-db.js: AgBYChqcw9S6miqPGyUeyiLh9kxQC3diTx6SQ4d2tFHX7yuwFZt4r3UPvDpb7eZOa9G2bV1bPUfoWfmv9/nZEp152q7gQSx2dUph4uGKlWuIzHjbkrLRnZ/ECZBS68mPZG3a//irYRCeBbcNirOQkbs0NaC/bv/xiasLXgZtsekSWlTcoEUv5B2Ihw6DfvNMtykzqJlu1gAhMiI7zGVZupRYqAOzJm/wssMzKqkZx7JfbEn1OfehxNLZwBRlXJ6LpllAkyVZyxgI0iDy1XX1YkAhT7SbXBpWoMRL1Jgw/356P6mXEbKoMGLxZU7/299BHPeCyL5CSO7KSQ4UPUv2kRvWqQHw0mFVAu6TTIx1m6ZM8yMu77iSm6fPO6vu4S8NHxtPOxmy24kbfSAw0fW5MajjFJ9psnA1Iccdq+MbCS6pDOwQog9gMveWcDaSSVMSfqPWNQUcnllY/mUSbWVw8Ypt1ck3sdLgX/07a/eAp914fF49PGSLlpVSWDIUgpTC5QGe5prJF/7qYQ2BWvdkNkZYPGtd6pjZFhkYSslSyjgyq1MOIQwu/JLK4vtjMZXrUyeeRiZ0WzKoU44enCMrHFXUdPf7hDPqSjPah2QYRTBB49I0fh6kAXIcXpttH6RmpgJ976CcVghBYncWXRt27ZMIRiouDkk6eVuu7bKbmK8J9Fg9QmO0a/aEyWIMramPDVS9LGciX6IkK67KQLIECnQz9xP5lUJ2CYgC7Lhp2mnf3MMFLCtcusQ/sKLsS75V85tllcWiSZ3I5Gl4MU9hdNb6Jx88XfoxKC3oxQZd61BHQ88Ip+oj9rfiJ3DJAcv+8CEJPMieQD1akFV+03OQys1gIteeDCM1ZqezsMYcNvw5d8Kve6ZizHJ4m0OV1UxgaOfqS6gPnu9hJTYmmJB0y7vlCSo+ey0kOYzJMwBUYALif7oZc8Or4jSax6YTwy5QjkH8AGzLSMMCVlYjwIOB0pWb3IX3W+P/
  template:
    metadata:
      name: mongo-init-script
      namespace: production
