---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-init-script
  namespace: production
spec:
  encryptedData:
    init-db.js: AgAyFLWfdOj30XjSHIUCfSSg6uO8H0NOj4CvRDJ/+Rurmw4QsShN/LA7bmbCqwYL7V235WEysvcY8fQQhV59h26iLvbkHk6itjN2zR5bjEqlLvi5U35TbJCv6oyOFTDejDh3tjTSi0r242pFH2Qpqmg1rmhhPGV/cRu8Pwptw+Xig3G2sVx9JpPLkC/ikWek06ijyDoM9oDLfyR/yRz4CK+bk2gAFKPM+yM1ue0Rc+s+I94ruvoyQQ0cMIdknlL9ty77GmZnNzsNxl82qKyFOp5AnZZl2A0v0lfI7RH+VN1mSl+qFhsFb2gLZ4PuJsqfZ4FdVl7VYcnoUuNTzNgYzMVx2xkDubDuF6v+Bh8WZ5a6TFINdjG4+CFalVp4wGHaWIT+sSFvzFHPZZXq0RjafKi19rocbM8sVXA8x/4Eequ3AvkLhTKYjSPGMIftgsCMzjWGgoRio2UNtBaXeM3JsiHQf5nWiUvqP2R7675mW4PbTPVGsFdf04HApQOvtqEfe3DxbWotMurzHpVYC4QGVTv9fxCS4KPt4uskp0GogyQ8Gn0cZTrZguz4gHzyFxFUsCVms/RaesrWJr5LEbhivjphBpfWsyL6w1ebo3MCJy/1V/vYBReJ/ZgIp5xyzCG5Tn35q+tuqPcEvrxUo9+CUCueTnue5OAoLXBUU4YyOwNSvfXHYXC7zCbl7HLzFCRz1CrjQjQ8aDj4jSjWno2Iskzi/dCYr+4hbeo+4xUfPVKp+BCOq62S6/BVy/0ez8yMzul37Vo1peCmhNIIvVUZ3Lxv8UZWlkpcpHMmOZMe9GTYFepq6p0SIASblTg3iBhBrFIxRumkl/2vvLkKxpxX0zeino0BK/6Zd1mUEHCaLlLuTtKmv1wM6H8EsvzshvZ0nb6aw1zZbRB7cIebLV2DhetBuqqzgPdcGtr29K2cRoygVeCD3MG+oT8mNUgKTz2xRgVF2MLcccr7Fh2gdqsMr9I1l0c9I2XG
  template:
    metadata:
      name: mongo-init-script
      namespace: production
