---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-init-script
  namespace: production
spec:
  encryptedData:
    init-db.js: AgBIuuHr9d6BrmvqXik9eD0UPYtOu+6THkSeK+ZhNt2TKdJjdk7dey+ljSgoDCfNmQ+DI98qC8phhu3QA90iz0ux4r1Unkh7QRSO52WucOvWM1JgAA65QZs6jwG+9Le3zJ5hwsTjZqfX7a1XfRbzOuYFAYtrEokcp6rrhuAbJDVStAioS1hVkAWky30N7KAcsYTJoqzAYPsBEDPLL0nSckg1/4q41P9pQku4kKkIzkg5ura+fkXf9LouGoJ8lvCyYDqiADu00iHCciI4MHKk6UXT+Omboz/OME0fYUPcSFe35m9OqIDYMDsxbAMp5qMTCVzs/H78qlvwpzKN/MLxqxe5KVDPOTvJ/UtzOkXiO9eb7d+b7NDRiOOsQrHS4Kn3kweCBWThDc1MiA4BrmAISsHkHtmCrsqsniVa1pXZFYzoZvE+kjMa3d/1dLlP/7it3NKzxNSO6OiM5Qm0cnqh8lyMxHC6MZg7s0cQm9XIV7e+0d5ctrwjT+AhrWwaJLmgCLWh44MBkWcdBUeyM3MmZh5vWMi8h2uJiVRiqAp7cJpOBSEMd1RTwYfGSutoldPJ21/irijXqNlFTGvqIgKvaHF48SnQ6+HFGbmv/PclcgCj+retQVBGnYYRukRhTggkTloa8RgIRWMrXcRlyojAP9Yn1rCqxXElgW3jR9j909liwNdqiBw7jNO6Z3P1Q007LThk5uKgoRNjwc1R9F+tPfbvuxxYhTSFb9V1CrBMCR0yNUzErOkV5BGMDGTqlfapV9ESYfMc4nmOdIx1IlnF2MkCP96TYrNn1pKhhlrsCQMqLKp0MRYYFrfCA61dvSaaG8r0JGIoUSu6oTouspA7XE0JVDIKlNqjd7zTywEPKCAbtr9HW7LrjcTEQtK3C3nCuH+X44TYbgwLrXYuFZjc5TOBmS4z6yJkg1E1vUwhtokrHjctfK/xAyYdvBllOMl0qXOIogx57KdX0608PUfakKA1M8OVa9Sm
  template:
    metadata:
      name: mongo-init-script
      namespace: production
