apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  ports:
    - name: https
      port: 443
      targetPort: 443
    - name: siderolink
      port: 8090
      targetPort: 8090
    - name: eventsink
      port: 8091
      targetPort: 8091