apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - omni-ingress.yaml
  - auth-ingress.yaml
  - omni-service-endpoints.yaml
  - omni-auth-service-endpoints.yaml