apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb-native.yaml
  - metallb-bgp.yaml
patches:
  - path: metallb-more-power.yaml
  - path: metallb-ignore-label.yaml