name: Update infra

on:
  schedule:
    - cron: "0 0 * * *"  # Ежедневно в полночь
  workflow_dispatch:      # Возможность ручного запуска

permissions:
  contents: write
  pull-requests: write
  actions: "write"
jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@v2

      - name: Run Updatecli in Dry Run mode
        run: updatecli diff --config updatecli/updatecli.d
        env:
          GITHUB_TOKEN  : ${{ secrets.GITHUB_TOKEN }}

      - name: Run Updatecli in Apply mode
        run: updatecli apply --config updatecli/updatecli.d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}